### ISSUE TITLE
esml newline parsing on windows fails

### ISSUE THREAD

**Issue by TomKaltz** [Rotorsoft/esml#1]
**Describe the bug**
esml fails to parse due to windows line return formatting.  I used the test-project.esml provided with the package to test.

```
yarn create-eventually-app --project=test-project
yarn run v1.22.19
$ C:\Users\tomka\WebstormProjects\2023\esml\node_modules\.bin\create-eventually-app --project=test-project
C:\Users\tomka\WebstormProjects\2023\esml\node_modules\@rotorsoft\esml\dist\parser.js:27
        throw new ParseError(source(), expected, actual.length > 30 ? actual.substring(0, 40) + "..." : actual);
        ^

ParseError: Parser error at line 1: Expected identifier but got
    at error (C:\Users\tomka\WebstormProjects\2023\esml\node_modules\@rotorsoft\esml\dist\parser.js:27:15)
    at nextToken (C:\Users\tomka\WebstormProjects\2023\esml\node_modules\@rotorsoft\esml\dist\parser.js:72:17)
    at parse (C:\Users\tomka\WebstormProjects\2023\esml\node_modules\@rotorsoft\esml\dist\parser.js:122:16)
    at generateContexts (C:\Users\tomka\WebstormProjects\2023\esml\node_modules\@rotorsoft\esml\dist\cli\generators.js:300:47)
 at Object.<anonymous> (C:\Users\tomka\WebstormProjects\2023\esml\node_modules\@rotorsoft\esml\dist\cli\create-eventually-app.js:21:35)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  source: { from: { line: 1, col: 0 }, to: { line: 1, col: 0 } },
  expected: 'identifier',
  actual: '\r'
}

Node.js v18.13.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior**
I expect the esml to parse properly and generate the eventually contexts

**Screenshots**

- OS: Windows 10

**Comment by Rotorsoft** [comment]
Haha, windows and \r ... I miss that 🤣 ... probably a quick fix, but I need to find a windows machine first

**Comment by TomKaltz** [comment]
Fixed by https://github.com/Rotorsoft/esml/commit/a479d46344ae316294eb01ce63eab1221398fa65#diff-abe2818e9c29aadf84401cb7ef8286c7cbce9253eba09f6fa52e22ca4e57b17eR60
